In [1]:
import numpy as np
import pandas as pd
data=pd.read_csv('Telco-Customer-Churn.csv')

In [2]:
data

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [4]:
data['TotalCharges'] = pd.to_numeric(data['TotalCharges'], errors='coerce')

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [6]:
data.describe()

       SeniorCitizen       tenure  MonthlyCharges  TotalCharges
count    7043.000000  7043.000000     7043.000000   7032.000000
mean        0.162147    32.371149       64.761692   2283.300441
std         0.368612    24.559481       30.090047   2266.771362
min         0.000000     0.000000       18.250000     18.800000
25%         0.000000     9.000000       35.500000    401.450000
50%         0.000000    29.000000       70.350000   1397.475000
75%         0.000000    55.000000       89.850000   3794.737500
max         1.000000    72.000000      118.750000   8684.800000

In [7]:
no_of_nul=list(data.isnull().sum())

In [8]:
data['TotalCharges'].fillna(value=0, inplace=True)

In [9]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [10]:
non_numerical_columns=data.select_dtypes(include=['object']).columns

In [11]:
non_numerical_columns

Index(['customerID', 'gender', 'Partner', 'Dependents', 'PhoneService',
       'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'Contract', 'PaperlessBilling', 'PaymentMethod', 'Churn'],
      dtype='object')

In [12]:
data1=data
for column in non_numerical_columns:
    data1[column + '_LabelEncoded']=label_encoder.fit_transform(data1[column])
    data1=data1.drop(column,axis=1)
print(data1)

      SeniorCitizen  tenure  MonthlyCharges  TotalCharges  \
0                 0       1           29.85         29.85
1                 0      34           56.95       1889.50
2                 0       2           53.85        108.15
3                 0      45           42.30       1840.75
4                 0       2           70.70        151.65
...             ...     ...             ...           ...
7038              0      24           84.80       1990.50
7039              0      72          103.20       7362.90
7040              0      11           29.60        346.45
7041              1       4           74.40        306.60
7042              0      66          105.65       6844.50

      customerID_LabelEncoded  gender_LabelEncoded  Partner_LabelEncoded  \
0                        5375                    0                     1
1                        3962                    1                     0
2                        2564                    1                     0
3                        5535                    1                     0
4                        6511                    0                     0
...                       ...                  ...                   ...
7038                     4853                    1                     1
7039                     1525                    0                     1
7040                     3367                    0                     1
7041                     5934                    1                     1
7042                     2226                    1                     0

      Dependents_LabelEncoded  PhoneService_LabelEncoded  \
0                           0                          0
1                           0                          1
2                           0                          1
3                           0                          0
4                           0                          1
...                       ...                        ...
7038                        1                          1
7039                        1                          1
7040                        1                          0
7041                        0                          1
7042                        0                          1

      MultipleLines_LabelEncoded  ...  OnlineSecurity_LabelEncoded  \
0                              1  ...                            0
1                              0  ...                            2
2                              0  ...                            2
3                              1  ...                            2
4                              0  ...                            0
...                          ...  ...                          ...
7038                           2  ...                            2
7039                           2  ...                            0
7040                           1  ...                            2
7041                           2  ...                            0
7042                           0  ...                            2

      OnlineBackup_LabelEncoded  DeviceProtection_LabelEncoded  \
0                             2                              0
1                             0                              2
2                             2                              0
3                             0                              2
4                             0                              0
...                         ...                            ...
7038                          0                              2
7039                          2                              2
7040                          0                              0
7041                          0                              0
7042                          0                              2

      TechSupport_LabelEncoded  StreamingTV_LabelEncoded  \
0                            0                         0
1                            0                         0
2                            0                         0
3                            2                         0
4                            0                         0
...                        ...                       ...
7038                         2                         2
7039                         0                         2
7040                         0                         0
7041                         0                         0
7042                         2                         2

      StreamingMovies_LabelEncoded  Contract_LabelEncoded  \
0                                0                      0
1                                0                      1
2                                0                      0
3                                0                      1
4                                0                      0
...                            ...                    ...
7038                             2                      1
7039                             2                      1
7040                             0                      0
7041                             0                      0
7042                             2                      2

      PaperlessBilling_LabelEncoded  PaymentMethod_LabelEncoded  \
0                                 1                           2
1                                 0                           3
2                                 1                           3
3                                 0                           0
4                                 1                           2
...                             ...                         ...
7038                              1                           3
7039                              1                           1
7040                              1                           2
7041                              1                           3
7042                              1                           0

      Churn_LabelEncoded
0                      0
1                      0
2                      1
3                      0
4                      1
...                  ...
7038                   0
7039                   0
7040                   0
7041                   1
7042                   0

[7043 rows x 21 columns]

In [13]:
data1

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,customerID_LabelEncoded,gender_LabelEncoded,Partner_LabelEncoded,Dependents_LabelEncoded,PhoneService_LabelEncoded,MultipleLines_LabelEncoded,...,OnlineSecurity_LabelEncoded,OnlineBackup_LabelEncoded,DeviceProtection_LabelEncoded,TechSupport_LabelEncoded,StreamingTV_LabelEncoded,StreamingMovies_LabelEncoded,Contract_LabelEncoded,PaperlessBilling_LabelEncoded,PaymentMethod_LabelEncoded,Churn_LabelEncoded
0,0,1,29.85,29.85,5375,0,1,0,0,1,...,0,2,0,0,0,0,0,1,2,0
1,0,34,56.95,1889.50,3962,1,0,0,1,0,...,2,0,2,0,0,0,1,0,3,0
2,0,2,53.85,108.15,2564,1,0,0,1,0,...,2,2,0,0,0,0,0,1,3,1
3,0,45,42.30,1840.75,5535,1,0,0,0,1,...,2,0,2,2,0,0,1,0,0,0
4,0,2,70.70,151.65,6511,0,0,0,1,0,...,0,0,0,0,0,0,0,1,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,24,84.80,1990.50,4853,1,1,1,1,2,...,2,0,2,2,2,2,1,1,3,0
7039,0,72,103.20,7362.90,1525,0,1,1,1,2,...,0,2,2,0,2,2,1,1,1,0
7040,0,11,29.60,346.45,3367,0,1,1,0,1,...,2,0,0,0,0,0,0,1,2,0
7041,1,4,74.40,306.60,5934,1,1,0,1,2,...,0,0,0,0,0,0,0,1,3,1
7042,0,66,105.65,6844.50,2226,1,0,0,1,0,...,2,0,2,2,2,2,2,1,0,0

In [14]:
X = data1.iloc[:,:-1].values
y = data1.iloc[:,-1].values

# SVM

In [15]:
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)
from sklearn.svm import SVC
model=SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.7193563653573118

# Decision tree

In [16]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

X = data1.iloc[:,:-1].values
Y = data1.iloc[:,-1].values

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3)

clf = DecisionTreeClassifier()
clf.fit(X_train, Y_train)

Y_pred = clf.predict(X_test)

accuracy = accuracy_score(Y_test, Y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.7198296261239944

In [17]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100,criterion='gini',random_state=0)

In [18]:
from sklearn.model_selection import GridSearchCV
param={
    'n_estimators':[10, 50, 100],
    'criterion':['gini','entropy'],
    'bootstrap':[True, False]
}

In [19]:
cls_grid = RandomForestClassifier(random_state=0)
gr = GridSearchCV(cls_grid, param, cv=10, n_jobs=-1)

In [20]:
gr.fit(X_train,y_train)
print(gr.best_params_)

{'bootstrap': True, 'criterion': 'gini', 'n_estimators': 50}

randomised search cv

In [21]:
from sklearn.linear_model import LogisticRegression
reg = LogisticRegression()
from sklearn.model_selection import RandomizedSearchCV

In [22]:

clf = RandomizedSearchCV(cls_grid, param, cv=10, n_jobs=-1)
search = clf.fit(X_train,y_train)

In [23]:
search.best_params_

{'n_estimators': 50, 'criterion': 'gini', 'bootstrap': True}

# Random forest

In [24]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

x = data1.iloc[:,:-1].values
y = data1.iloc[:,-1].values
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
rfc = RandomForestClassifier(n_estimators=100,criterion='gini')
rfc.fit(x_train,y_train)
y_pred = rfc.predict(x_test)
print(accuracy_score(y_test,y_pred))

0.7870326549929011

In [25]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100,criterion='gini',random_state=0)

In [26]:
from sklearn.model_selection import GridSearchCV
param={
    'n_estimators':[10, 50, 100],
    'criterion':['gini','entropy'],
    'bootstrap':[True, False]
}

In [27]:
cls_grid = RandomForestClassifier(random_state=0)
gr = GridSearchCV(cls_grid, param, cv=10, n_jobs=-1)

In [28]:
gr.fit(X_train,y_train)
print(gr.best_params_)

{'bootstrap': True, 'criterion': 'entropy', 'n_estimators': 100}

randomised search cv

In [29]:
from sklearn.linear_model import LogisticRegression
reg = LogisticRegression()
from sklearn.model_selection import RandomizedSearchCV

In [30]:

clf = RandomizedSearchCV(cls_grid, param, cv=10, n_jobs=-1)
search = clf.fit(X_train,y_train)

In [31]:
search.best_params_

{'n_estimators': 100, 'criterion': 'entropy', 'bootstrap': True}

# Adaboost

In [32]:
# Load libraries
from sklearn.ensemble import AdaBoostClassifier
# Import train_test_split function
from sklearn.model_selection import train_test_split
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Load data
x = data1.iloc[:,:-1].values
y = data1.iloc[:,-1].values
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

abc = AdaBoostClassifier(n_estimators=50,learning_rate=1)
model = abc.fit(x_train, y_train)

y_pred = model.predict(x_test)

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.7917652626597255