In [24]:
import numpy as np
import pandas as pd
data=pd.read_csv('house_pred.csv')

In [25]:
data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [26]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [27]:
data.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

# finding number of null values

In [28]:
no_of_nul=list(data.isnull().sum())
nul_columns=list()

In [29]:
for i in range(len(no_of_nul)):
    if no_of_nul[i]!=0:
        nul_columns.append(data.columns[i])

In [30]:
nul_columns

['LotFrontage',
 'Alley',
 'MasVnrType',
 'MasVnrArea',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'FireplaceQu',
 'GarageType',
 'GarageYrBlt',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PoolQC',
 'Fence',
 'MiscFeature']

In [31]:
for i in nul_columns:
    print(i,'         ',data[i].dtypes)
#     print(data[i].dtypes)

LotFrontage           float64
Alley           object
MasVnrType           object
MasVnrArea           float64
BsmtQual           object
BsmtCond           object
BsmtExposure           object
BsmtFinType1           object
BsmtFinType2           object
Electrical           object
FireplaceQu           object
GarageType           object
GarageYrBlt           float64
GarageFinish           object
GarageQual           object
GarageCond           object
PoolQC           object
Fence           object
MiscFeature           object

In [32]:
# data['LotFrontage'].fillna(data['LotFrontage'].mean(),inplace=True)
# data['LotFrontage'].describe()

# finding numerical columns

In [33]:
numerical_columns=data.select_dtypes(include=['int64','float64']).columns

In [34]:
numerical_columns

Index(['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd',
       'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF',
       'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea',
       'MiscVal', 'MoSold', 'YrSold', 'SalePrice'],
      dtype='object')

# finding number of numerical null columns

In [35]:
numerical_nul_columns = []

for i in range(len(numerical_columns)):
        print(data[numerical_columns[i]].isnull().sum())
        if data[numerical_columns[i]].isnull().sum() != 0:
               numerical_nul_columns.append(numerical_columns[i])
        

numerical_nul_columns

0
0
259
0
0
0
0
0
8
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
81
0
0
0
0
0
0
0
0
0
0
0
0

['LotFrontage', 'MasVnrArea', 'GarageYrBlt']

In [36]:
numerical_nul_columns

['LotFrontage', 'MasVnrArea', 'GarageYrBlt']

# filling or replacing null values with appropriate values in numerical_nul_columns

In [37]:
data['LotFrontage'].describe()

count    1201.000000
mean       70.049958
std        24.284752
min        21.000000
25%        59.000000
50%        69.000000
75%        80.000000
max       313.000000
Name: LotFrontage, dtype: float64

In [38]:
data['GarageYrBlt'].describe()

count    1379.000000
mean     1978.506164
std        24.689725
min      1900.000000
25%      1961.000000
50%      1980.000000
75%      2002.000000
max      2010.000000
Name: GarageYrBlt, dtype: float64

In [39]:
data['MasVnrArea'].describe()

count    1452.000000
mean      103.685262
std       181.066207
min         0.000000
25%         0.000000
50%         0.000000
75%       166.000000
max      1600.000000
Name: MasVnrArea, dtype: float64

In [40]:
data['LotFrontage'].fillna(data['LotFrontage'].mean(),inplace=True)
data['LotFrontage'].describe()

/var/folders/2n/ktry640n7b9858mzxq1hrbth0000gn/T/ipykernel_12267/2269196025.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['LotFrontage'].fillna(data['LotFrontage'].mean(),inplace=True)

count    1460.000000
mean       70.049958
std        22.024023
min        21.000000
25%        60.000000
50%        70.049958
75%        79.000000
max       313.000000
Name: LotFrontage, dtype: float64

In [41]:
data['GarageYrBlt'].fillna(data['GarageYrBlt'].mean(),inplace=True)
data['GarageYrBlt'].describe()

/var/folders/2n/ktry640n7b9858mzxq1hrbth0000gn/T/ipykernel_12267/3923649440.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['GarageYrBlt'].fillna(data['GarageYrBlt'].mean(),inplace=True)

count    1460.000000
mean     1978.506164
std        23.994583
min      1900.000000
25%      1962.000000
50%      1978.506164
75%      2001.000000
max      2010.000000
Name: GarageYrBlt, dtype: float64

In [42]:
data['MasVnrArea'].fillna(0,inplace=True)
data['MasVnrArea'].describe()

/var/folders/2n/ktry640n7b9858mzxq1hrbth0000gn/T/ipykernel_12267/590044653.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['MasVnrArea'].fillna(0,inplace=True)

count    1460.000000
mean      103.117123
std       180.731373
min         0.000000
25%         0.000000
50%         0.000000
75%       164.250000
max      1600.000000
Name: MasVnrArea, dtype: float64

# Categorical null value columns

In [43]:
non_numerical_columns=data.select_dtypes(include=['object']).columns
len(non_numerical_columns)

43

In [44]:
non_numerical_columns

Index(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
       'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature',
       'SaleType', 'SaleCondition'],
      dtype='object')

In [45]:
non_numerical_nul_columns = []
for i in range(len(non_numerical_columns)):
    print(data[non_numerical_columns[i]].isnull().sum())
    if data[non_numerical_columns[i]].isnull().sum() != 0:
        non_numerical_nul_columns.append(non_numerical_columns[i])
        
    
non_numerical_nul_columns

0
0
1369
0
0
0
0
0
0
0
0
0
0
0
0
0
0
872
0
0
0
37
37
38
37
38
0
0
0
1
0
0
690
81
81
81
81
0
1453
1179
1406
0
0

['Alley',
 'MasVnrType',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PoolQC',
 'Fence',
 'MiscFeature']

# Analysing non numerical null colums to drop or fill null with appropriate values

In [46]:
data['Alley'].value_counts()

Alley
Grvl    50
Pave    41
Name: count, dtype: int64

In [47]:
data['MasVnrType'].value_counts()

MasVnrType
BrkFace    445
Stone      128
BrkCmn      15
Name: count, dtype: int64

In [48]:
for i in non_numerical_nul_columns:
    print(data[i].value_counts())
    print()

Alley
Grvl    50
Pave    41
Name: count, dtype: int64

MasVnrType
BrkFace    445
Stone      128
BrkCmn      15
Name: count, dtype: int64

BsmtQual
TA    649
Gd    618
Ex    121
Fa     35
Name: count, dtype: int64

BsmtCond
TA    1311
Gd      65
Fa      45
Po       2
Name: count, dtype: int64

BsmtExposure
No    953
Av    221
Gd    134
Mn    114
Name: count, dtype: int64

BsmtFinType1
Unf    430
GLQ    418
ALQ    220
BLQ    148
Rec    133
LwQ     74
Name: count, dtype: int64

BsmtFinType2
Unf    1256
Rec      54
LwQ      46
BLQ      33
ALQ      19
GLQ      14
Name: count, dtype: int64

Electrical
SBrkr    1334
FuseA      94
FuseF      27
FuseP       3
Mix         1
Name: count, dtype: int64

FireplaceQu
Gd    380
TA    313
Fa     33
Ex     24
Po     20
Name: count, dtype: int64

GarageType
Attchd     870
Detchd     387
BuiltIn     88
Basment     19
CarPort      9
2Types       6
Name: count, dtype: int64

GarageFinish
Unf    605
RFn    422
Fin    352
Name: count, dtype: int64

GarageQual
TA    1311
Fa      48
Gd      14
Ex       3
Po       3
Name: count, dtype: int64

GarageCond
TA    1326
Fa      35
Gd       9
Po       7
Ex       2
Name: count, dtype: int64

PoolQC
Gd    3
Ex    2
Fa    2
Name: count, dtype: int64

Fence
MnPrv    157
GdPrv     59
GdWo      54
MnWw      11
Name: count, dtype: int64

MiscFeature
Shed    49
Gar2     2
Othr     2
TenC     1
Name: count, dtype: int64

# Filling and droping non numerical columns that has null values

In [49]:
data=data.drop('Alley', axis=1) #dropping Alley column

In [50]:
data['MasVnrType'].fillna(method='ffill', inplace=True)

/var/folders/2n/ktry640n7b9858mzxq1hrbth0000gn/T/ipykernel_12267/3501790972.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['MasVnrType'].fillna(method='ffill', inplace=True)
/var/folders/2n/ktry640n7b9858mzxq1hrbth0000gn/T/ipykernel_12267/3501790972.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['MasVnrType'].fillna(method='ffill', inplace=True)

In [51]:
#do not type data=data['MasVnrType'].fillna(method='ffill') because the function returns series. Only if u type inplace=True 
#the same dataframe would be changed

In [52]:
#filling MasVnrType's null value with previously present value

In [53]:
data['BsmtQual'].fillna(method='ffill', inplace=True)

/var/folders/2n/ktry640n7b9858mzxq1hrbth0000gn/T/ipykernel_12267/2516333853.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['BsmtQual'].fillna(method='ffill', inplace=True)
/var/folders/2n/ktry640n7b9858mzxq1hrbth0000gn/T/ipykernel_12267/2516333853.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['BsmtQual'].fillna(method='ffill', inplace=True)

In [54]:
data['BsmtCond'].fillna(method='ffill', inplace=True)

/var/folders/2n/ktry640n7b9858mzxq1hrbth0000gn/T/ipykernel_12267/3938368923.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['BsmtCond'].fillna(method='ffill', inplace=True)
/var/folders/2n/ktry640n7b9858mzxq1hrbth0000gn/T/ipykernel_12267/3938368923.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['BsmtCond'].fillna(method='ffill', inplace=True)

In [55]:
data['BsmtExposure'].fillna(method='ffill', inplace=True)

/var/folders/2n/ktry640n7b9858mzxq1hrbth0000gn/T/ipykernel_12267/2145491041.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['BsmtExposure'].fillna(method='ffill', inplace=True)
/var/folders/2n/ktry640n7b9858mzxq1hrbth0000gn/T/ipykernel_12267/2145491041.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['BsmtExposure'].fillna(method='ffill', inplace=True)

In [56]:
data['BsmtFinType1'].fillna(method='ffill', inplace=True)

/var/folders/2n/ktry640n7b9858mzxq1hrbth0000gn/T/ipykernel_12267/770247994.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['BsmtFinType1'].fillna(method='ffill', inplace=True)
/var/folders/2n/ktry640n7b9858mzxq1hrbth0000gn/T/ipykernel_12267/770247994.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['BsmtFinType1'].fillna(method='ffill', inplace=True)

In [57]:
data['BsmtFinType2'].fillna(method='ffill', inplace=True)

/var/folders/2n/ktry640n7b9858mzxq1hrbth0000gn/T/ipykernel_12267/121573348.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['BsmtFinType2'].fillna(method='ffill', inplace=True)
/var/folders/2n/ktry640n7b9858mzxq1hrbth0000gn/T/ipykernel_12267/121573348.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['BsmtFinType2'].fillna(method='ffill', inplace=True)

In [58]:
data['Electrical'].fillna(method='ffill', inplace=True)

/var/folders/2n/ktry640n7b9858mzxq1hrbth0000gn/T/ipykernel_12267/3916229034.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Electrical'].fillna(method='ffill', inplace=True)
/var/folders/2n/ktry640n7b9858mzxq1hrbth0000gn/T/ipykernel_12267/3916229034.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['Electrical'].fillna(method='ffill', inplace=True)

In [59]:
data=data.drop('FireplaceQu', axis=1) #as almost half of the column is null

In [60]:
data['GarageType'].fillna('Attchd', inplace=True)

/var/folders/2n/ktry640n7b9858mzxq1hrbth0000gn/T/ipykernel_12267/988188871.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['GarageType'].fillna('Attchd', inplace=True)

In [61]:
data['GarageFinish'].fillna('Unf', inplace=True)

/var/folders/2n/ktry640n7b9858mzxq1hrbth0000gn/T/ipykernel_12267/3381584158.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['GarageFinish'].fillna('Unf', inplace=True)

In [62]:
data['GarageQual'].fillna('TA', inplace=True)

/var/folders/2n/ktry640n7b9858mzxq1hrbth0000gn/T/ipykernel_12267/2421907168.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['GarageQual'].fillna('TA', inplace=True)

In [63]:
data['GarageCond'].fillna('TA', inplace=True)

/var/folders/2n/ktry640n7b9858mzxq1hrbth0000gn/T/ipykernel_12267/3316052025.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['GarageCond'].fillna('TA', inplace=True)

In [64]:
data=data.drop('PoolQC', axis=1)

In [65]:
data=data.drop('Fence', axis=1)

In [66]:
data=data.drop('MiscFeature', axis=1)

In [67]:
# data['MiscFeature'].isna().sum()

In [68]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 76 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1460 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   LotShape       1460 non-null   object
 7   LandContour    1460 non-null   object
 8   Utilities      1460 non-null   object
 9   LotConfig      1460 non-null   object
 10  LandSlope      1460 non-null   object
 11  Neighborhood   1460 non-null   object
 12  Condition1     1460 non-null   object
 13  Condition2     1460 non-null   object
 14  BldgType       1460 non-null   object
 15  HouseStyle     1460 non-null   object
 16  OverallQual    1460 non-null   int64
 17  OverallCond    1460 non-null   int64
 18  YearBuilt      1460 non-null   int64
 19  YearRemodAdd   1460 non-null   int64
 20  RoofStyle      1460 non-null   object
 21  RoofMatl       1460 non-null   object
 22  Exterior1st    1460 non-null   object
 23  Exterior2nd    1460 non-null   object
 24  MasVnrType     1460 non-null   object
 25  MasVnrArea     1460 non-null   float64
 26  ExterQual      1460 non-null   object
 27  ExterCond      1460 non-null   object
 28  Foundation     1460 non-null   object
 29  BsmtQual       1460 non-null   object
 30  BsmtCond       1460 non-null   object
 31  BsmtExposure   1460 non-null   object
 32  BsmtFinType1   1460 non-null   object
 33  BsmtFinSF1     1460 non-null   int64
 34  BsmtFinType2   1460 non-null   object
 35  BsmtFinSF2     1460 non-null   int64
 36  BsmtUnfSF      1460 non-null   int64
 37  TotalBsmtSF    1460 non-null   int64
 38  Heating        1460 non-null   object
 39  HeatingQC      1460 non-null   object
 40  CentralAir     1460 non-null   object
 41  Electrical     1460 non-null   object
 42  1stFlrSF       1460 non-null   int64
 43  2ndFlrSF       1460 non-null   int64
 44  LowQualFinSF   1460 non-null   int64
 45  GrLivArea      1460 non-null   int64
 46  BsmtFullBath   1460 non-null   int64
 47  BsmtHalfBath   1460 non-null   int64
 48  FullBath       1460 non-null   int64
 49  HalfBath       1460 non-null   int64
 50  BedroomAbvGr   1460 non-null   int64
 51  KitchenAbvGr   1460 non-null   int64
 52  KitchenQual    1460 non-null   object
 53  TotRmsAbvGrd   1460 non-null   int64
 54  Functional     1460 non-null   object
 55  Fireplaces     1460 non-null   int64
 56  GarageType     1460 non-null   object
 57  GarageYrBlt    1460 non-null   float64
 58  GarageFinish   1460 non-null   object
 59  GarageCars     1460 non-null   int64
 60  GarageArea     1460 non-null   int64
 61  GarageQual     1460 non-null   object
 62  GarageCond     1460 non-null   object
 63  PavedDrive     1460 non-null   object
 64  WoodDeckSF     1460 non-null   int64
 65  OpenPorchSF    1460 non-null   int64
 66  EnclosedPorch  1460 non-null   int64
 67  3SsnPorch      1460 non-null   int64
 68  ScreenPorch    1460 non-null   int64
 69  PoolArea       1460 non-null   int64
 70  MiscVal        1460 non-null   int64
 71  MoSold         1460 non-null   int64
 72  YrSold         1460 non-null   int64
 73  SaleType       1460 non-null   object
 74  SaleCondition  1460 non-null   object
 75  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(38)
memory usage: 867.0+ KB

# drop unnecessary columns mannually by checking each and every column

In [69]:
dropping_list=['Heating','HeatingQC','GarageYrBlt','GarageCars','KitchenAbvGr','GarageQual',
              'ExterQual','OverallQual','LotConfig','Street','Utilities','CentralAir','PoolArea','MoSold','PavedDrive',
              'GarageCond','RoofMatl','ExterCond','BsmtCond','RoofStyle','PoolArea']

#PoolArea,

In [70]:
data=data.drop(columns=dropping_list)

In [71]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 56 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1460 non-null   float64
 4   LotArea        1460 non-null   int64
 5   LotShape       1460 non-null   object
 6   LandContour    1460 non-null   object
 7   LandSlope      1460 non-null   object
 8   Neighborhood   1460 non-null   object
 9   Condition1     1460 non-null   object
 10  Condition2     1460 non-null   object
 11  BldgType       1460 non-null   object
 12  HouseStyle     1460 non-null   object
 13  OverallCond    1460 non-null   int64
 14  YearBuilt      1460 non-null   int64
 15  YearRemodAdd   1460 non-null   int64
 16  Exterior1st    1460 non-null   object
 17  Exterior2nd    1460 non-null   object
 18  MasVnrType     1460 non-null   object
 19  MasVnrArea     1460 non-null   float64
 20  Foundation     1460 non-null   object
 21  BsmtQual       1460 non-null   object
 22  BsmtExposure   1460 non-null   object
 23  BsmtFinType1   1460 non-null   object
 24  BsmtFinSF1     1460 non-null   int64
 25  BsmtFinType2   1460 non-null   object
 26  BsmtFinSF2     1460 non-null   int64
 27  BsmtUnfSF      1460 non-null   int64
 28  TotalBsmtSF    1460 non-null   int64
 29  Electrical     1460 non-null   object
 30  1stFlrSF       1460 non-null   int64
 31  2ndFlrSF       1460 non-null   int64
 32  LowQualFinSF   1460 non-null   int64
 33  GrLivArea      1460 non-null   int64
 34  BsmtFullBath   1460 non-null   int64
 35  BsmtHalfBath   1460 non-null   int64
 36  FullBath       1460 non-null   int64
 37  HalfBath       1460 non-null   int64
 38  BedroomAbvGr   1460 non-null   int64
 39  KitchenQual    1460 non-null   object
 40  TotRmsAbvGrd   1460 non-null   int64
 41  Functional     1460 non-null   object
 42  Fireplaces     1460 non-null   int64
 43  GarageType     1460 non-null   object
 44  GarageFinish   1460 non-null   object
 45  GarageArea     1460 non-null   int64
 46  WoodDeckSF     1460 non-null   int64
 47  OpenPorchSF    1460 non-null   int64
 48  EnclosedPorch  1460 non-null   int64
 49  3SsnPorch      1460 non-null   int64
 50  ScreenPorch    1460 non-null   int64
 51  MiscVal        1460 non-null   int64
 52  YrSold         1460 non-null   int64
 53  SaleType       1460 non-null   object
 54  SaleCondition  1460 non-null   object
 55  SalePrice      1460 non-null   int64
dtypes: float64(2), int64(30), object(24)
memory usage: 638.9+ KB

# finding corelation between target column and other numerical column and removing the columns that has correlation coefficient less than 0.5

In [72]:
numerical_columns2=data.select_dtypes(include=['int64','float64']).columns

In [73]:
numerical_columns2 = numerical_columns2[:-1]

In [74]:
numerical_columns2

Index(['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallCond',
       'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2',
       'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageArea',
       'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'MiscVal', 'YrSold'],
      dtype='object')

In [75]:
s='SalePrice'
value=list()
for i in numerical_columns2:
    value.append(abs(data[i].corr(data[s])))




#nul_columns.append(data.columns[i])

In [86]:
value

[0.02191671944343111,
 0.08428413512659517,
 0.3349008515405507,
 0.2638433538714056,
 0.077855894048678,
 0.5228973328794968,
 0.5071009671113862,
 0.47261449900457386,
 0.3864198062421531,
 0.011378121450215137,
 0.2144791055469689,
 0.6135805515591954,
 0.6058521846919145,
 0.3193338028320677,
 0.025606130000679548,
 0.7086244776126521,
 0.22712223313149438,
 0.01684415429735901,
 0.5606637627484456,
 0.2841076755947825,
 0.16821315430074002,
 0.5337231555820281,
 0.46692883675152796,
 0.6234314389183616,
 0.3244134445681296,
 0.3158562271160552,
 0.12857795792595658,
 0.04458366533574843,
 0.11144657114291115,
 0.021189579640303245,
 0.028922585168730287]

In [76]:
    
keys=numerical_columns2
values=value
correlation_dict={}
# for i in range(len(keys)):
#     correlation_dict[keys[i]]=values[i]

correlation_dict=dict(zip(keys, values))
print(correlation_dict)

{'Id': 0.02191671944343111, 'MSSubClass': 0.08428413512659517, 'LotFrontage': 0.3349008515405507, 'LotArea': 0.2638433538714056, 'OverallCond': 0.077855894048678, 'YearBuilt': 0.5228973328794968, 'YearRemodAdd': 0.5071009671113862, 'MasVnrArea': 0.47261449900457386, 'BsmtFinSF1': 0.3864198062421531, 'BsmtFinSF2': 0.011378121450215137, 'BsmtUnfSF': 0.2144791055469689, 'TotalBsmtSF': 0.6135805515591954, '1stFlrSF': 0.6058521846919145, '2ndFlrSF': 0.3193338028320677, 'LowQualFinSF': 0.025606130000679548, 'GrLivArea': 0.7086244776126521, 'BsmtFullBath': 0.22712223313149438, 'BsmtHalfBath': 0.01684415429735901, 'FullBath': 0.5606637627484456, 'HalfBath': 0.2841076755947825, 'BedroomAbvGr': 0.16821315430074002, 'TotRmsAbvGrd': 0.5337231555820281, 'Fireplaces': 0.46692883675152796, 'GarageArea': 0.6234314389183616, 'WoodDeckSF': 0.3244134445681296, 'OpenPorchSF': 0.3158562271160552, 'EnclosedPorch': 0.12857795792595658, '3SsnPorch': 0.04458366533574843, 'ScreenPorch': 0.11144657114291115, 'MiscVal': 0.021189579640303245, 'YrSold': 0.028922585168730287}

In [77]:
#finding columns whose corelation is greater than 0.5
below_corr_0_5=[key for key,value in correlation_dict.items() if value<0.5]
print(below_corr_0_5)

['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallCond', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', '2ndFlrSF', 'LowQualFinSF', 'BsmtFullBath', 'BsmtHalfBath', 'HalfBath', 'BedroomAbvGr', 'Fireplaces', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'MiscVal', 'YrSold']

In [78]:
data=data.drop(columns=below_corr_0_5)

In [79]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 33 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSZoning       1460 non-null   object
 1   LotShape       1460 non-null   object
 2   LandContour    1460 non-null   object
 3   LandSlope      1460 non-null   object
 4   Neighborhood   1460 non-null   object
 5   Condition1     1460 non-null   object
 6   Condition2     1460 non-null   object
 7   BldgType       1460 non-null   object
 8   HouseStyle     1460 non-null   object
 9   YearBuilt      1460 non-null   int64
 10  YearRemodAdd   1460 non-null   int64
 11  Exterior1st    1460 non-null   object
 12  Exterior2nd    1460 non-null   object
 13  MasVnrType     1460 non-null   object
 14  Foundation     1460 non-null   object
 15  BsmtQual       1460 non-null   object
 16  BsmtExposure   1460 non-null   object
 17  BsmtFinType1   1460 non-null   object
 18  BsmtFinType2   1460 non-null   object
 19  TotalBsmtSF    1460 non-null   int64
 20  Electrical     1460 non-null   object
 21  1stFlrSF       1460 non-null   int64
 22  GrLivArea      1460 non-null   int64
 23  FullBath       1460 non-null   int64
 24  KitchenQual    1460 non-null   object
 25  TotRmsAbvGrd   1460 non-null   int64
 26  Functional     1460 non-null   object
 27  GarageType     1460 non-null   object
 28  GarageFinish   1460 non-null   object
 29  GarageArea     1460 non-null   int64
 30  SaleType       1460 non-null   object
 31  SaleCondition  1460 non-null   object
 32  SalePrice      1460 non-null   int64
dtypes: int64(9), object(24)
memory usage: 376.5+ KB

In [80]:
data['MSZoning'].value_counts()

MSZoning
RL         1151
RM          218
FV           65
RH           16
C (all)      10
Name: count, dtype: int64

In [81]:
data

,MSZoning,LotShape,LandContour,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,YearBuilt,...,FullBath,KitchenQual,TotRmsAbvGrd,Functional,GarageType,GarageFinish,GarageArea,SaleType,SaleCondition,SalePrice
0,RL,Reg,Lvl,Gtl,CollgCr,Norm,Norm,1Fam,2Story,2003,...,2,Gd,8,Typ,Attchd,RFn,548,WD,Normal,208500
1,RL,Reg,Lvl,Gtl,Veenker,Feedr,Norm,1Fam,1Story,1976,...,2,TA,6,Typ,Attchd,RFn,460,WD,Normal,181500
2,RL,IR1,Lvl,Gtl,CollgCr,Norm,Norm,1Fam,2Story,2001,...,2,Gd,6,Typ,Attchd,RFn,608,WD,Normal,223500
3,RL,IR1,Lvl,Gtl,Crawfor,Norm,Norm,1Fam,2Story,1915,...,1,Gd,7,Typ,Detchd,Unf,642,WD,Abnorml,140000
4,RL,IR1,Lvl,Gtl,NoRidge,Norm,Norm,1Fam,2Story,2000,...,2,Gd,9,Typ,Attchd,RFn,836,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,RL,Reg,Lvl,Gtl,Gilbert,Norm,Norm,1Fam,2Story,1999,...,2,TA,7,Typ,Attchd,RFn,460,WD,Normal,175000
1456,RL,Reg,Lvl,Gtl,NWAmes,Norm,Norm,1Fam,1Story,1978,...,2,TA,7,Min1,Attchd,Unf,500,WD,Normal,210000
1457,RL,Reg,Lvl,Gtl,Crawfor,Norm,Norm,1Fam,2Story,1941,...,2,Gd,9,Typ,Attchd,RFn,252,WD,Normal,266500
1458,RL,Reg,Lvl,Gtl,NAmes,Norm,Norm,1Fam,1Story,1950,...,1,Gd,5,Typ,Attchd,Unf,240,WD,Normal,142125
1459,RL,Reg,Lvl,Gtl,Edwards,Norm,Norm,1Fam,1Story,1965,...,1,TA,6,Typ,Attchd,Fin,276,WD,Normal,147500

# Perform label encoding on column GarageFinish

In [82]:
#finding number of colums having object data type
non_numerical_columns_2=data.select_dtypes(include=['object']).columns

In [83]:
print(non_numerical_columns_2)
len(non_numerical_columns_2)

Index(['MSZoning', 'LotShape', 'LandContour', 'LandSlope', 'Neighborhood',
       'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'Foundation', 'BsmtQual', 'BsmtExposure',
       'BsmtFinType1', 'BsmtFinType2', 'Electrical', 'KitchenQual',
       'Functional', 'GarageType', 'GarageFinish', 'SaleType',
       'SaleCondition'],
      dtype='object')

24

In [84]:
data1=data
# for i in non_numerical_columns_2:
len(data1.columns)

33

In [85]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
for column in non_numerical_columns_2:
    data1[column + '_LabelEncoded']=label_encoder.fit_transform(data1[column])
    data1=data1.drop(column,axis=1)
print(data1)
# len(data1.columns)

ModuleNotFoundError: No module named 'sklearn'

In [ ]:
data1

,YearBuilt,YearRemodAdd,TotalBsmtSF,1stFlrSF,GrLivArea,FullBath,TotRmsAbvGrd,GarageArea,SalePrice,MSZoning_LabelEncoded,...,BsmtExposure_LabelEncoded,BsmtFinType1_LabelEncoded,BsmtFinType2_LabelEncoded,Electrical_LabelEncoded,KitchenQual_LabelEncoded,Functional_LabelEncoded,GarageType_LabelEncoded,GarageFinish_LabelEncoded,SaleType_LabelEncoded,SaleCondition_LabelEncoded
0,2003,2003,856,856,1710,2,8,548,208500,3,...,3,2,5,4,2,6,1,1,8,4
1,1976,1976,1262,1262,1262,2,6,460,181500,3,...,1,0,5,4,3,6,1,1,8,4
2,2001,2002,920,920,1786,2,6,608,223500,3,...,2,2,5,4,2,6,1,1,8,4
3,1915,1970,756,961,1717,1,7,642,140000,3,...,3,0,5,4,2,6,5,2,8,0
4,2000,2000,1145,1145,2198,2,9,836,250000,3,...,0,2,5,4,2,6,1,1,8,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1999,2000,953,953,1647,2,7,460,175000,3,...,3,5,5,4,3,6,1,1,8,4
1456,1978,1988,1542,2073,2073,2,7,500,210000,3,...,3,0,4,4,3,2,1,2,8,4
1457,1941,2006,1152,1188,2340,2,9,252,266500,3,...,3,2,5,4,2,6,1,1,8,4
1458,1950,1996,1078,1078,1078,1,5,240,142125,3,...,2,2,4,0,2,6,1,2,8,4
1459,1965,1965,1256,1256,1256,1,6,276,147500,3,...,3,1,3,4,3,6,1,0,8,4

# Rearrange the column for quick processing

In [ ]:
column_to_move='SalePrice'
columns_except_target=[col for col in data1.columns if col!=column_to_move]
data1=data1[columns_except_target + [column_to_move]]
print(data1)

      YearBuilt  YearRemodAdd  TotalBsmtSF  1stFlrSF  GrLivArea  FullBath  \
0          2003          2003          856       856       1710         2
1          1976          1976         1262      1262       1262         2
2          2001          2002          920       920       1786         2
3          1915          1970          756       961       1717         1
4          2000          2000         1145      1145       2198         2
...         ...           ...          ...       ...        ...       ...
1455       1999          2000          953       953       1647         2
1456       1978          1988         1542      2073       2073         2
1457       1941          2006         1152      1188       2340         2
1458       1950          1996         1078      1078       1078         1
1459       1965          1965         1256      1256       1256         1

      TotRmsAbvGrd  GarageArea  MSZoning_LabelEncoded  LotShape_LabelEncoded  \
0                8         548                      3                      3
1                6         460                      3                      3
2                6         608                      3                      0
3                7         642                      3                      0
4                9         836                      3                      0
...            ...         ...                    ...                    ...
1455             7         460                      3                      3
1456             7         500                      3                      3
1457             9         252                      3                      3
1458             5         240                      3                      3
1459             6         276                      3                      3

      ...  BsmtFinType1_LabelEncoded  BsmtFinType2_LabelEncoded  \
0     ...                          2                          5
1     ...                          0                          5
2     ...                          2                          5
3     ...                          0                          5
4     ...                          2                          5
...   ...                        ...                        ...
1455  ...                          5                          5
1456  ...                          0                          4
1457  ...                          2                          5
1458  ...                          2                          4
1459  ...                          1                          3

      Electrical_LabelEncoded  KitchenQual_LabelEncoded  \
0                           4                         2
1                           4                         3
2                           4                         2
3                           4                         2
4                           4                         2
...                       ...                       ...
1455                        4                         3
1456                        4                         3
1457                        4                         2
1458                        0                         2
1459                        4                         3

      Functional_LabelEncoded  GarageType_LabelEncoded  \
0                           6                        1
1                           6                        1
2                           6                        1
3                           6                        5
4                           6                        1
...                       ...                      ...
1455                        6                        1
1456                        2                        1
1457                        6                        1
1458                        6                        1
1459                        6                        1

      GarageFinish_LabelEncoded  SaleType_LabelEncoded  \
0                             1                      8
1                             1                      8
2                             1                      8
3                             2                      8
4                             1                      8
...                         ...                    ...
1455                          1                      8
1456                          2                      8
1457                          1                      8
1458                          2                      8
1459                          0                      8

      SaleCondition_LabelEncoded  SalePrice
0                              4     208500
1                              4     181500
2                              4     223500
3                              0     140000
4                              4     250000
...                          ...        ...
1455                           4     175000
1456                           4     210000
1457                           4     266500
1458                           4     142125
1459                           4     147500

[1460 rows x 33 columns]

In [ ]:
data1.columns

Index(['YearBuilt', 'YearRemodAdd', 'TotalBsmtSF', '1stFlrSF', 'GrLivArea',
       'FullBath', 'TotRmsAbvGrd', 'GarageArea', 'MSZoning_LabelEncoded',
       'LotShape_LabelEncoded', 'LandContour_LabelEncoded',
       'LandSlope_LabelEncoded', 'Neighborhood_LabelEncoded',
       'Condition1_LabelEncoded', 'Condition2_LabelEncoded',
       'BldgType_LabelEncoded', 'HouseStyle_LabelEncoded',
       'Exterior1st_LabelEncoded', 'Exterior2nd_LabelEncoded',
       'MasVnrType_LabelEncoded', 'Foundation_LabelEncoded',
       'BsmtQual_LabelEncoded', 'BsmtExposure_LabelEncoded',
       'BsmtFinType1_LabelEncoded', 'BsmtFinType2_LabelEncoded',
       'Electrical_LabelEncoded', 'KitchenQual_LabelEncoded',
       'Functional_LabelEncoded', 'GarageType_LabelEncoded',
       'GarageFinish_LabelEncoded', 'SaleType_LabelEncoded',
       'SaleCondition_LabelEncoded', 'SalePrice'],
      dtype='object')

In [ ]:
x = data1.iloc[:,:-1].values
y = data1.iloc[:,-1].values
x = pd.DataFrame(x)

In [ ]:
x.columns=['YearBuilt', 'YearRemodAdd', 'TotalBsmtSF', '1stFlrSF', 'GrLivArea',
       'FullBath', 'TotRmsAbvGrd', 'GarageArea', 'MSZoning_LabelEncoded',
       'LotShape_LabelEncoded', 'LandContour_LabelEncoded',
       'LandSlope_LabelEncoded', 'Neighborhood_LabelEncoded',
       'Condition1_LabelEncoded', 'Condition2_LabelEncoded',
       'BldgType_LabelEncoded', 'HouseStyle_LabelEncoded',
       'Exterior1st_LabelEncoded', 'Exterior2nd_LabelEncoded',
       'MasVnrType_LabelEncoded', 'Foundation_LabelEncoded',
       'BsmtQual_LabelEncoded', 'BsmtExposure_LabelEncoded',
       'BsmtFinType1_LabelEncoded', 'BsmtFinType2_LabelEncoded',
       'Electrical_LabelEncoded', 'KitchenQual_LabelEncoded',
       'Functional_LabelEncoded', 'GarageType_LabelEncoded',
       'GarageFinish_LabelEncoded', 'SaleType_LabelEncoded',
       'SaleCondition_LabelEncoded']

In [ ]:
x

,YearBuilt,YearRemodAdd,TotalBsmtSF,1stFlrSF,GrLivArea,FullBath,TotRmsAbvGrd,GarageArea,MSZoning_LabelEncoded,LotShape_LabelEncoded,...,BsmtExposure_LabelEncoded,BsmtFinType1_LabelEncoded,BsmtFinType2_LabelEncoded,Electrical_LabelEncoded,KitchenQual_LabelEncoded,Functional_LabelEncoded,GarageType_LabelEncoded,GarageFinish_LabelEncoded,SaleType_LabelEncoded,SaleCondition_LabelEncoded
0,2003,2003,856,856,1710,2,8,548,3,3,...,3,2,5,4,2,6,1,1,8,4
1,1976,1976,1262,1262,1262,2,6,460,3,3,...,1,0,5,4,3,6,1,1,8,4
2,2001,2002,920,920,1786,2,6,608,3,0,...,2,2,5,4,2,6,1,1,8,4
3,1915,1970,756,961,1717,1,7,642,3,0,...,3,0,5,4,2,6,5,2,8,0
4,2000,2000,1145,1145,2198,2,9,836,3,0,...,0,2,5,4,2,6,1,1,8,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1999,2000,953,953,1647,2,7,460,3,3,...,3,5,5,4,3,6,1,1,8,4
1456,1978,1988,1542,2073,2073,2,7,500,3,3,...,3,0,4,4,3,2,1,2,8,4
1457,1941,2006,1152,1188,2340,2,9,252,3,3,...,3,2,5,4,2,6,1,1,8,4
1458,1950,1996,1078,1078,1078,1,5,240,3,3,...,2,2,4,0,2,6,1,2,8,4
1459,1965,1965,1256,1256,1256,1,6,276,3,3,...,3,1,3,4,3,6,1,0,8,4

# manually add intercept column

In [ ]:
x['intercept']=1

In [ ]:
vif = pd.DataFrame()
vif['variable']= x.columns

# get the VIF values

In [ ]:
vif = pd.DataFrame()
vif['variable']= x.columns
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif['vif']=[variance_inflation_factor(x.values,i) for i in range(x.shape[1])]

In [ ]:
vif

                      variable           vif
0                    YearBuilt      4.044960
1                 YearRemodAdd      2.015362
2                  TotalBsmtSF      3.856465
3                     1stFlrSF      4.611736
4                    GrLivArea      5.292984
5                     FullBath      2.306455
6                 TotRmsAbvGrd      3.552802
7                   GarageArea      2.022526
8        MSZoning_LabelEncoded      1.241108
9        LotShape_LabelEncoded      1.152710
10    LandContour_LabelEncoded      1.246595
11      LandSlope_LabelEncoded      1.273222
12   Neighborhood_LabelEncoded      1.190783
13     Condition1_LabelEncoded      1.070338
14     Condition2_LabelEncoded      1.032553
15       BldgType_LabelEncoded      1.257639
16     HouseStyle_LabelEncoded      1.711317
17    Exterior1st_LabelEncoded      3.828752
18    Exterior2nd_LabelEncoded      3.854262
19     MasVnrType_LabelEncoded      1.126100
20     Foundation_LabelEncoded      1.902791
21       BsmtQual_LabelEncoded      1.893105
22   BsmtExposure_LabelEncoded      1.354798
23   BsmtFinType1_LabelEncoded      1.197870
24   BsmtFinType2_LabelEncoded      1.076331
25     Electrical_LabelEncoded      1.243003
26    KitchenQual_LabelEncoded      1.640524
27     Functional_LabelEncoded      1.127946
28     GarageType_LabelEncoded      1.565617
29   GarageFinish_LabelEncoded      1.873627
30       SaleType_LabelEncoded      1.102975
31  SaleCondition_LabelEncoded      1.143652
32                   intercept  27744.921398

# drop off the intercept column

In [ ]:
x = x.drop(['intercept'], axis=1)

# Train data

In [ ]:
x=x.values

In [ ]:
#here we do not have to use sklearn to segregate train and test data as already test data is given

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3, random_state=0)

In [ ]:
x_train.shape, x_test.shape

((1022, 32), (438, 32))

# Test data

In [ ]:
data2=pd.read_csv('test.csv')

In [ ]:
len(data2.columns)

80

In [ ]:
data2['BsmtQual'].fillna(method='ffill', inplace=True)

In [ ]:
data2['BsmtCond'].fillna(method='ffill', inplace=True)

In [ ]:
data2['BsmtExposure'].fillna(method='ffill', inplace=True)

In [ ]:
data2['BsmtFinType1'].fillna(method='ffill', inplace=True)

In [ ]:
data2['BsmtFinType2'].fillna(method='ffill', inplace=True)

In [ ]:
data2['Electrical'].fillna(method='ffill', inplace=True)

In [ ]:
data2['GarageType'].fillna('Attchd', inplace=True)

In [ ]:
data2['GarageFinish'].fillna('Unf', inplace=True)

In [ ]:
data2['GarageQual'].fillna('TA', inplace=True)

In [ ]:
# data=data.drop(columns=below_corr_0_5)
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 256 entries, 0 to 255
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             256 non-null    int64
 1   MSSubClass     256 non-null    int64
 2   MSZoning       256 non-null    object
 3   LotFrontage    207 non-null    float64
 4   LotArea        256 non-null    int64
 5   Street         256 non-null    object
 6   Alley          16 non-null     object
 7   LotShape       256 non-null    object
 8   LandContour    256 non-null    object
 9   Utilities      256 non-null    object
 10  LotConfig      256 non-null    object
 11  LandSlope      256 non-null    object
 12  Neighborhood   256 non-null    object
 13  Condition1     256 non-null    object
 14  Condition2     256 non-null    object
 15  BldgType       256 non-null    object
 16  HouseStyle     256 non-null    object
 17  OverallQual    256 non-null    int64
 18  OverallCond    256 non-null    int64
 19  YearBuilt      256 non-null    int64
 20  YearRemodAdd   256 non-null    int64
 21  RoofStyle      256 non-null    object
 22  RoofMatl       256 non-null    object
 23  Exterior1st    256 non-null    object
 24  Exterior2nd    256 non-null    object
 25  MasVnrType     254 non-null    object
 26  MasVnrArea     254 non-null    float64
 27  ExterQual      256 non-null    object
 28  ExterCond      256 non-null    object
 29  Foundation     256 non-null    object
 30  BsmtQual       256 non-null    object
 31  BsmtCond       256 non-null    object
 32  BsmtExposure   256 non-null    object
 33  BsmtFinType1   256 non-null    object
 34  BsmtFinSF1     256 non-null    int64
 35  BsmtFinType2   256 non-null    object
 36  BsmtFinSF2     256 non-null    int64
 37  BsmtUnfSF      256 non-null    int64
 38  TotalBsmtSF    256 non-null    int64
 39  Heating        256 non-null    object
 40  HeatingQC      256 non-null    object
 41  CentralAir     256 non-null    object
 42  Electrical     256 non-null    object
 43  1stFlrSF       256 non-null    int64
 44  2ndFlrSF       256 non-null    int64
 45  LowQualFinSF   256 non-null    int64
 46  GrLivArea      256 non-null    int64
 47  BsmtFullBath   256 non-null    int64
 48  BsmtHalfBath   256 non-null    int64
 49  FullBath       256 non-null    int64
 50  HalfBath       256 non-null    int64
 51  BedroomAbvGr   256 non-null    int64
 52  KitchenAbvGr   256 non-null    int64
 53  KitchenQual    256 non-null    object
 54  TotRmsAbvGrd   256 non-null    int64
 55  Functional     256 non-null    object
 56  Fireplaces     256 non-null    int64
 57  FireplaceQu    132 non-null    object
 58  GarageType     256 non-null    object
 59  GarageYrBlt    242 non-null    float64
 60  GarageFinish   256 non-null    object
 61  GarageCars     256 non-null    int64
 62  GarageArea     256 non-null    int64
 63  GarageQual     256 non-null    object
 64  GarageCond     242 non-null    object
 65  PavedDrive     256 non-null    object
 66  WoodDeckSF     256 non-null    int64
 67  OpenPorchSF    256 non-null    int64
 68  EnclosedPorch  256 non-null    int64
 69  3SsnPorch      256 non-null    int64
 70  ScreenPorch    256 non-null    int64
 71  PoolArea       256 non-null    int64
 72  PoolQC         3 non-null      object
 73  Fence          54 non-null     object
 74  MiscFeature    6 non-null      object
 75  MiscVal        256 non-null    int64
 76  MoSold         256 non-null    int64
 77  YrSold         256 non-null    int64
 78  SaleType       256 non-null    object
 79  SaleCondition  256 non-null    object
dtypes: float64(3), int64(34), object(43)
memory usage: 160.1+ KB

In [ ]:
data2=data2.drop('MiscFeature', axis=1)

In [ ]:
data2=data2.drop('PoolQC', axis=1)

In [ ]:
data2=data2.drop('Fence', axis=1)

In [ ]:
data2=data2.drop('FireplaceQu', axis=1)

In [ ]:
data2=data2.drop('Alley', axis=1)

In [ ]:
dropping_columns_final=['Heating','HeatingQC','GarageYrBlt','GarageCars','KitchenAbvGr','GarageQual',
              'ExterQual','OverallQual','LotConfig','Street','Utilities','CentralAir','PoolArea','MoSold','PavedDrive',
              'GarageCond','RoofMatl','ExterCond','BsmtCond','RoofStyle','PoolArea']



# ['Heating','HeatingQC','GarageYrBlt','GarageCars','KitchenAbvGr','GarageQual',
#               'ExterQual','OverallQual','LotConfig','Street','Utilities','CentralAir','PoolArea','MoSold','PavedDrive',
#               'GarageCond','RoofMatl','ExterCond','BsmtCond','RoofStyle','PoolArea','MSZoning', 'LotShape', 'LandContour', 'LandSlope', 'Neighborhood',
#        'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'Exterior1st',
#        'Exterior2nd', 'MasVnrType', 'Foundation', 'BsmtQual', 'BsmtExposure',
#        'BsmtFinType1', 'BsmtFinType2', 'Electrical', 'KitchenQual',
#        'Functional', 'GarageType', 'GarageFinish', 'SaleType',
#        'SaleCondition']

In [ ]:
len(dropping_columns_final)

21

In [ ]:
data2=data2.drop(columns=dropping_list)

In [ ]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 256 entries, 0 to 255
Data columns (total 55 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             256 non-null    int64
 1   MSSubClass     256 non-null    int64
 2   MSZoning       256 non-null    object
 3   LotFrontage    207 non-null    float64
 4   LotArea        256 non-null    int64
 5   LotShape       256 non-null    object
 6   LandContour    256 non-null    object
 7   LandSlope      256 non-null    object
 8   Neighborhood   256 non-null    object
 9   Condition1     256 non-null    object
 10  Condition2     256 non-null    object
 11  BldgType       256 non-null    object
 12  HouseStyle     256 non-null    object
 13  OverallCond    256 non-null    int64
 14  YearBuilt      256 non-null    int64
 15  YearRemodAdd   256 non-null    int64
 16  Exterior1st    256 non-null    object
 17  Exterior2nd    256 non-null    object
 18  MasVnrType     254 non-null    object
 19  MasVnrArea     254 non-null    float64
 20  Foundation     256 non-null    object
 21  BsmtQual       256 non-null    object
 22  BsmtExposure   256 non-null    object
 23  BsmtFinType1   256 non-null    object
 24  BsmtFinSF1     256 non-null    int64
 25  BsmtFinType2   256 non-null    object
 26  BsmtFinSF2     256 non-null    int64
 27  BsmtUnfSF      256 non-null    int64
 28  TotalBsmtSF    256 non-null    int64
 29  Electrical     256 non-null    object
 30  1stFlrSF       256 non-null    int64
 31  2ndFlrSF       256 non-null    int64
 32  LowQualFinSF   256 non-null    int64
 33  GrLivArea      256 non-null    int64
 34  BsmtFullBath   256 non-null    int64
 35  BsmtHalfBath   256 non-null    int64
 36  FullBath       256 non-null    int64
 37  HalfBath       256 non-null    int64
 38  BedroomAbvGr   256 non-null    int64
 39  KitchenQual    256 non-null    object
 40  TotRmsAbvGrd   256 non-null    int64
 41  Functional     256 non-null    object
 42  Fireplaces     256 non-null    int64
 43  GarageType     256 non-null    object
 44  GarageFinish   256 non-null    object
 45  GarageArea     256 non-null    int64
 46  WoodDeckSF     256 non-null    int64
 47  OpenPorchSF    256 non-null    int64
 48  EnclosedPorch  256 non-null    int64
 49  3SsnPorch      256 non-null    int64
 50  ScreenPorch    256 non-null    int64
 51  MiscVal        256 non-null    int64
 52  YrSold         256 non-null    int64
 53  SaleType       256 non-null    object
 54  SaleCondition  256 non-null    object
dtypes: float64(2), int64(29), object(24)
memory usage: 110.1+ KB

In [ ]:
numerical_columns3=data2.select_dtypes(include=['int64','float64']).columns

In [ ]:
numerical_columns3

Index(['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallCond',
       'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2',
       'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageArea',
       'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'MiscVal', 'YrSold'],
      dtype='object')

In [ ]:
data2=data2.drop(columns=below_corr_0_5)

In [ ]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 256 entries, 0 to 255
Data columns (total 32 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSZoning       256 non-null    object
 1   LotShape       256 non-null    object
 2   LandContour    256 non-null    object
 3   LandSlope      256 non-null    object
 4   Neighborhood   256 non-null    object
 5   Condition1     256 non-null    object
 6   Condition2     256 non-null    object
 7   BldgType       256 non-null    object
 8   HouseStyle     256 non-null    object
 9   YearBuilt      256 non-null    int64
 10  YearRemodAdd   256 non-null    int64
 11  Exterior1st    256 non-null    object
 12  Exterior2nd    256 non-null    object
 13  MasVnrType     254 non-null    object
 14  Foundation     256 non-null    object
 15  BsmtQual       256 non-null    object
 16  BsmtExposure   256 non-null    object
 17  BsmtFinType1   256 non-null    object
 18  BsmtFinType2   256 non-null    object
 19  TotalBsmtSF    256 non-null    int64
 20  Electrical     256 non-null    object
 21  1stFlrSF       256 non-null    int64
 22  GrLivArea      256 non-null    int64
 23  FullBath       256 non-null    int64
 24  KitchenQual    256 non-null    object
 25  TotRmsAbvGrd   256 non-null    int64
 26  Functional     256 non-null    object
 27  GarageType     256 non-null    object
 28  GarageFinish   256 non-null    object
 29  GarageArea     256 non-null    int64
 30  SaleType       256 non-null    object
 31  SaleCondition  256 non-null    object
dtypes: int64(8), object(24)
memory usage: 64.1+ KB

In [ ]:
for column in non_numerical_columns_2:
    data2[column + '_LabelEncoded']=label_encoder.fit_transform(data2[column])
    data2=data2.drop(column,axis=1)

In [ ]:
data2

,YearBuilt,YearRemodAdd,TotalBsmtSF,1stFlrSF,GrLivArea,FullBath,TotRmsAbvGrd,GarageArea,MSZoning_LabelEncoded,LotShape_LabelEncoded,...,BsmtExposure_LabelEncoded,BsmtFinType1_LabelEncoded,BsmtFinType2_LabelEncoded,Electrical_LabelEncoded,KitchenQual_LabelEncoded,Functional_LabelEncoded,GarageType_LabelEncoded,GarageFinish_LabelEncoded,SaleType_LabelEncoded,SaleCondition_LabelEncoded
0,1975,1975,1056,1074,1074,1,6,495,3,3,...,3,0,5,2,3,4,0,1,3,3
1,1990,1991,2158,2196,2196,2,7,701,3,0,...,2,0,1,2,2,4,0,1,3,3
2,1966,1966,1056,1056,1056,1,5,384,2,3,...,3,4,5,2,3,4,4,2,3,3
3,2003,2003,1682,1700,1700,2,7,544,3,3,...,0,2,5,2,2,4,0,1,3,3
4,1962,1980,931,1283,1283,1,6,506,3,3,...,3,4,1,2,3,4,4,2,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251,1999,2000,953,953,1647,2,7,460,3,3,...,3,5,5,2,3,4,0,1,3,3
252,1978,1988,1542,2073,2073,2,7,500,3,3,...,3,0,4,2,3,1,0,2,3,3
253,1941,2006,1152,1188,2340,2,9,252,3,3,...,3,2,5,2,2,4,0,1,3,3
254,1950,1996,1078,1078,1078,1,5,240,3,3,...,2,2,4,0,2,4,0,2,3,3
255,1965,1965,1256,1256,1256,1,6,276,3,3,...,3,1,3,2,3,4,0,0,3,3

In [ ]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()

In [ ]:
reg.fit(x_train,y_train)

LinearRegression()

In [ ]:
reg.intercept_, reg.coef_

(-988701.5436688423,
 array([ 3.40071465e+02,  2.22863358e+02,  3.17008262e+01,  3.48701575e+00,
         7.68834876e+01, -6.72496593e+03, -1.21676909e+03,  3.39002154e+01,
         7.93276892e+02, -1.07985281e+03,  2.86635967e+03,  5.89098530e+03,
         2.89135567e+02, -2.14249759e+03, -4.11536516e+04, -4.23728456e+03,
        -7.23512579e+02, -5.84363923e+02,  6.79276867e+02,  2.05887649e+03,
        -1.29266817e+03, -1.31015529e+04, -2.91453244e+03, -2.80912471e+03,
         3.77603103e+02,  1.36246019e+03, -1.30285055e+04,  6.78136807e+03,
         9.79482697e+01, -3.39698766e+03, -7.31795355e+02,  4.97432995e+03]))

In [ ]:
y_pred = reg.predict(x_test)

In [ ]:
x_test, y_test

(array([[1957, 1975, 2035, ...,    1,    8,    2],
        [1941, 1950,  806, ...,    2,    8,    4],
        [1950, 1950,  709, ...,    2,    8,    4],
        ...,
        [1995, 1995, 2109, ...,    0,    8,    4],
        [2002, 2002, 1573, ...,    1,    8,    4],
        [2009, 2010, 2330, ...,    0,    6,    5]]),
 array([200624, 133000, 110000, 192000,  88000,  85000, 282922, 141000,
        745000, 148800, 208900, 136905, 225000, 123000, 119200, 145000,
        190000, 123600, 149350, 155000, 166000, 144500, 110000, 174000,
        185000, 168000, 177500,  84500, 320000, 118500, 110000, 213000,
        156000, 250000, 372500, 175000, 277500, 112500, 263000, 325000,
        243000, 130000, 164990, 280000, 403000, 119000, 125000, 128200,
        172500,  84900, 412500, 156000, 167900, 100000, 275000, 123000,
        132000, 239900, 139000, 115000, 137500, 135000, 134450, 180500,
        193500, 156500, 132000, 224500, 139000, 225000, 188500, 118000,
         82000, 392000, 112000, 248900, 134500,  79500, 320000, 158000,
        140000, 136500, 107500, 145000, 200500, 185000, 105000, 202665,
        186000, 136000, 200500, 190000, 187500, 200000, 172500, 157000,
        213000, 185000, 124500, 162900, 260000, 198500, 120000, 159500,
        105900, 260000, 143000, 106500, 178900, 127000,  90350, 118500,
        190000, 119900, 183900, 155000, 386250, 133000, 193500, 270000,
        141000, 146000, 128500, 176000, 214000, 222000, 415298, 187750,
        199900, 180000, 206300, 194000, 142953, 182900, 116050, 213250,
        139500, 179000, 107900, 175900, 158500, 145000, 217000, 150500,
        108959, 165600, 201000, 145500, 319900, 215000, 180500, 367294,
        239000, 145900, 161000, 250000,  89471, 230000, 147000, 163900,
         97000, 142000, 197000, 129000, 232000, 115000, 175000, 265000,
        207000, 181000, 176000, 171000, 196000, 176000, 113000, 139000,
        135000, 240000, 112000, 134000, 316600, 170000, 116000, 306000,
         82500, 175000, 106000, 194000, 194201, 155900, 138000, 177000,
        214000, 148000, 127000, 142500,  80000, 145000, 171000, 122500,
        139000, 189000, 120500, 124000, 160000, 200000, 160000, 313000,
        275000,  67000, 159000, 251000,  92900, 109500, 385000, 129000,
         82500, 301000, 249700,  81000, 187500, 110000, 117000, 128500,
        213490, 284000, 230500, 190000, 135000, 152000,  87500, 155000,
        115000, 144000, 248000, 132500, 136000, 117000,  82000, 157500,
        110000, 181000, 192500, 223500, 181500, 170000, 187500, 185900,
        160000, 192000, 181900, 266000,  99900, 438780, 229456, 216837,
        110500, 175900, 538000, 160000, 172500, 108000, 131500, 106250,
        385000, 370878, 345000,  68500, 250000, 245350, 125000, 234000,
        145000, 181000, 104000, 233000, 164000, 219500, 195000, 108000,
        149900, 315000, 177500, 140000, 193879, 137900, 118000, 324000,
        555000, 136000,  82500, 101000, 314813, 109500, 163500, 271000,
        205000, 185000, 160000, 155000,  91000, 131000, 165400, 194700,
        155000, 140000, 147000, 194000, 179540, 173000, 109500, 173733,
        129900, 119000, 125500, 149300, 305000, 102000, 178740, 129500,
         79900, 278000, 118400, 197000, 140000, 226000, 132500, 315000,
        224000, 132500, 119500, 215000, 210000, 200141, 185000, 149900,
        129000, 184100, 135000, 128000, 374000, 164000, 157000, 215000,
        165000, 144000, 125500,  98300,  91300, 135960, 226700, 333168,
        114500,  97000, 181000, 465000, 290000, 175000, 235000, 277000,
        325000, 178000, 235000, 239000,  85000, 107500, 160000, 145000,
        192140, 181000, 380000,  66500, 124500, 124000, 144000,  52500,
        217000, 275000, 127000, 262500, 162000, 103000, 137500, 127500,
        127000,  91000, 145000, 186500, 221500, 253293, 108480, 127000,
        237500,  86000, 141000, 176000, 178400, 173900, 157000, 193000,
        335000, 201000, 146500,  86000, 148000, 280000, 112000, 303477,
        250000, 244600, 126000, 130500, 241000, 118500, 115000, 129900,
        202500, 118000, 335000, 125000, 255900, 342643, 109008, 148500,
        132500, 110000, 244000, 115000, 194500, 129500, 167500, 227875,
        169900, 241500, 127500, 350000, 227000, 611657]))

In [ ]:
reg.score(x_test, y_test)

0.6696991167926125

In [ ]:
y_pred

array([ 204743.3008642 ,  170801.0983968 ,  115879.65662208,
        220729.84597067,   76012.66351056,   87685.11270141,
        231088.07022637,  129180.81108802,  519075.62119353,
        140148.93623209,  215501.23810785,   19863.36786763,
        237761.02264539,  118101.87565999,  119731.68946721,
        144535.23801487,  223278.54595317,  132374.04189711,
        158777.65200427,  185599.17906818,  149187.46669298,
        148417.04221686,   96332.73205148,  159490.49034031,
        201315.74112907,  170009.82174154,  178814.08313551,
         77730.56650392,  311314.42437408,   99685.27183863,
        170001.46090747,  206827.07430347,  145088.51376666,
        277677.28416479,  334658.27078533,  164900.67318986,
        268439.12103976,  108687.08867365,  242508.61402615,
        339190.61521718,  246058.98514941,  100612.30932602,
        218068.19544113,  309239.3331024 ,  351989.21008194,
        178782.45196707,  -87877.36860326,  112689.5882712 ,
        166619.64862305,   82989.18743309,  381945.74346957,
        137482.32704504,  185622.94784883,   41879.5213061 ,
        238632.78490328,  102928.1070969 ,  109227.78417193,
        221654.35938693,  133516.03287638,   94578.59899838,
        120597.67739502,  115644.86869223,  135117.24771936,
        141896.42251228,  229457.86953317,  177099.72986022,
        121170.12462989,  253517.2493636 ,  103714.71476576,
        209212.61657951,  190806.48922638,  191936.83673768,
         94179.88295783,  225282.64096948,   70399.42855213,
        261895.69055816,  122807.70630053,  110438.15766554,
        293741.59077051,  149509.29802082,  139505.95834935,
        120204.29441963,  134030.45597345,  157706.48536061,
        250734.13905887,  205505.6482725 ,  115287.35560462,
        195022.08223467,  193045.69686054,  121641.59040739,
        201828.74014284,  181388.84951026,  179416.12157305,
        225024.26576261,  215705.84450693,  150961.95994216,
        227513.15826734,  164603.24600079,  115381.73308618,
        139329.6048676 ,  263506.24699055,  177305.07218933,
        141686.78762216,  149525.26093711,   80528.50412582,
        258306.12601389,  172623.68238176,   85760.10353665,
        180393.16533215,  114165.39402794,   74263.57008717,
        114353.10828434,  184199.08674278,  124128.88518683,
        163475.78029723,  161937.66084827,  395815.00855835,
        136290.01285296,  223945.65098023,  258838.14594371,
        162179.70321529,  140430.46544723,  121029.26168002,
        187580.6909014 ,  242011.69622416,  269687.97664118,
        356021.77430249,  203648.58557951,  203355.59214218,
        178257.43732546,  181713.56740116,  204942.55718275,
        168754.82093201,  208586.26772003,   75575.0526015 ,
        217036.96919244,  121096.75160102,  180166.52212289,
        104013.39065314,  201727.17327089,  131481.76672647,
        140154.94887207,  241378.02576021,  161207.93073725,
        160197.64538972,  191154.41363029,  235613.26885495,
        152751.13275301,  287125.76162358,  226011.28750399,
        173452.39363331,  314690.60731866,  311781.33722401,
        181993.84096598,  149036.38428478,  284900.83152076,
        135115.69593064,  156006.84391098,  168755.31605702,
        161727.85357657,  100149.8094573 ,  126269.6169007 ,
        204424.80555958,  119839.93590365,  236793.68008258,
        142307.29940371,  155378.41588945,  278165.35995866,
        201741.34217478,  167414.9779455 ,  173427.56311087,
        156192.27696869,  214741.18262693,  174548.98741487,
        110894.73213171,  117941.19517589,  123028.4192039 ,
        275261.08669002,  116182.54342411,  138232.2536153 ,
        277045.42736273,  176564.68843968,  116802.43925389,
        284591.55279156,  104222.97797293,  169454.24567805,
         74762.42345895,  211166.173634  ,  239322.53386632,
        139663.31442459,  154656.18779777,  206905.26925406,
        227951.86332856,  152372.21339909,  172652.22890873,
        144129.87524479,   81512.42815913,  115448.7248969 ,
        167422.85914884,   98391.29537559,  100940.05552089,
        171906.60938801,  115239.81248955,  114547.87560268,
        133316.13037935,  249759.43095179,  152038.52664805,
        321962.35102528,  254684.47728112,   69707.37182191,
        168215.4130393 ,  251534.35000902,   71300.27538756,
         83463.62237837,  317890.65739207,  209910.86096114,
        175358.39262947,  301201.05511263,  260597.68150258,
         82798.37016882,  193787.28826554,  157611.05135739,
        148499.46316712,  106473.90268374,  203779.56158804,
        253663.09821933,  238868.96014742,  230977.6820516 ,
        145432.78096057,  154608.23462016,   48810.98081352,
        154454.40954676,  102594.43062247,  162698.62333171,
        226016.74954122,  113800.10802323,  153114.24494101,
        112962.40325793,   76276.97541282,  165492.7186965 ,
        117266.39194901,  180194.52420598,  217846.9934825 ,
        226070.45862128,  182868.23229039,  149823.07708409,
        186296.26940445,  199495.55863443,   88418.05704053,
        230830.75401851,  183101.35467709,  259104.85288837,
         92445.68731918,  353418.5326074 ,  216766.45456222,
        259431.46662565,  108870.81622297,  213363.0679398 ,
        395523.04675032,  785084.12013576,  184194.20167165,
        127996.3945328 ,  155971.78782265,   68030.7398506 ,
        294757.54734309,  319798.22652556,  351175.10130017,
       -137485.21306745,  217686.59915992,  258118.69639684,
        143872.28981342,  214452.39112436,  134569.22153082,
        190681.49497075,  141905.98779194,  253297.17941276,
        195403.21064818,  164349.13493601,  222543.50126582,
        120066.99680854,  100340.06042297,  346629.70876428,
        137311.79204184,  139307.64707612,  210402.31860432,
        211940.7265706 ,  105750.31335909,  248399.09621407,
        411449.10319715,  208605.98419934,   68375.38987753,
        116221.52104625,  302032.70145337,   90655.24227265,
        125427.95411011,  249048.01803539,  227880.83578724,
        188975.32685978,  118883.37665004,  171975.80533329,
        103771.63301092,  124295.29419499,  196465.33737865,
        210226.35145881,  159222.50818283,  142227.19553777,
        146694.16495382,  221402.1629815 ,  197775.68692831,
        185429.99973529,   79391.40378101,  175653.66970328,
        112545.10628331,  109470.44471479,  140724.19568663,
        145492.37931259,  295652.58104904,  148173.04170658,
        181347.68002569,  178820.37669262,   85207.96831011,
        251428.5671696 ,   82576.56259731,  263972.89590379,
        164079.77280275,  244211.09686752,  136438.2253026 ,
        333473.03415453,  209544.46776317,  147965.53910732,
        120223.01818478,  221494.44849476,  156962.15260328,
        212795.12755503,  165756.25991245,  153293.83546152,
        173503.01218305,  176427.16273944,  116510.83643395,
        113917.09633854,  325548.83122499,  180594.42492929,
        182815.03481425,  234080.0764732 ,  183061.88553641,
        145150.61309961,  131158.27189052,   59749.76947132,
         99603.88243772,  140346.18751303,  222373.41905924,
        300045.16749668,  103102.25555187,   80025.22110153,
        175270.36195827,  365743.73722943,  299042.41990975,
        187245.29292415,  230426.65191477,  255412.58633976,
        218093.89977635,  163114.7135363 ,  228995.44430521,
        244214.72018046,   79508.62636936,  160478.80855668,
        157526.09156785,  132699.14050494,  196434.37240855,
        178869.2428924 ,  363902.74805411,   81241.08699803,
        164729.26398679,  139776.87428243,  139534.2347535 ,
         79655.67769936,  226927.32624299,  259589.63641739,
        122514.05972111,  251119.59161026,  153322.58697504,
        115040.85434774,  131430.01347823,  127578.28469763,
        118134.60439612,   94786.40375902,  117391.68109692,
        201829.78818216,  261451.7098999 ,  362717.96558762,
         98845.22529888,  102763.61396953,  234714.29190062,
         65109.67929948,  137541.76831416,  181468.29929063,
        189927.83022935,  192775.31000539,  141988.0885987 ,
        177660.9434019 ,  338599.57875614,  253937.15345698,
        168003.01387869,  105909.845679  ,  147530.51569174,
        292480.97158436,  111790.74135666,  336248.87693109,
        245092.51602592,  242986.45388785,  166468.90066934,
        123662.12636623,  212939.47067122,  165713.86069477,
        108635.66793161,  113721.54520717,  220755.38286598,
        107411.11153149,  295951.67409826,   89851.30074495,
        260350.0246443 ,  334105.67413382,  101122.78323474,
        147475.94590467,  141498.82336329,  127030.68917491,
        288084.58438853,  142610.49049361,  210677.67481794,
        120211.12019694,  140519.9258961 ,  217077.66991049,
        150122.58475634,  179580.3933858 ,  181207.0588439 ,
        306391.84443112,  230098.39951171,  400327.34844694])